const ipaDict: Record<string, string> = {
  // Greetings & Farewells
  'hello': '/həˈloʊ/',
  'hi': '/haɪ/',
  'hey': '/heɪ/',
  'good morning': '/ˌɡʊd ˈmɔːr.nɪŋ/',
  'good afternoon': '/ˌɡʊd ˌæf.tərˈnuːn/',
  'good evening': '/ˌɡʊd ˈiːv.nɪŋ/',
  'good night': '/ˌɡʊd ˈnaɪt/',
  'welcome': '/ˈwel.kəm/',
  'goodbye': '/ˌɡʊdˈbaɪ/',
  'bye': '/baɪ/',
  'see you later': '/siː juː ˈleɪ.tər/',
  'see you': '/siː juː/',
  'take care': '/teɪk ker/',
  'have a nice day': '/hæv ə naɪs deɪ/',
  'how are you?': '/haʊ ɑːr juː/',
  "how are you doing?": '/haʊ ɑːr juː ˈduː.ɪŋ/',
  "how's it going?": '/haʊz ɪt ˈɡoʊ.ɪŋ/',
  "what's up?": '/wʌts ʌp/',
  'long time no see': '/lɔːŋ taɪm noʊ siː/',
  'nice to meet you': '/naɪs tə miːt juː/',
  'pleased to meet you': '/pliːzd tə miːt juː/',
  'nice to see you again': '/naɪs tə siː juː əˈɡen/',

  // Common responses & courtesy
  "i'm fine": '/aɪm faɪn/',
  "i'm good": '/aɪm ɡʊd/',
  "i'm great": '/aɪm ɡreɪt/',
  "i'm okay": '/aɪm oʊˈkeɪ/',
  'not bad': '/nɒt bæd/',
  'very well': '/ˈver.i wel/',
  'thank you': '/ˈθæŋk juː/',
  'thanks': '/θæŋks/',
  "you're welcome": '/jʊər ˈwel.kəm/',
  'please': '/pliːz/',
  'sorry': '/ˈsɒr.i/',
  'excuse me': '/ɪkˈskjuːz miː/',
  'of course': '/əv kɔːrs/',
  'no problem': '/noʊ ˈprɒb.ləm/',
  "don't worry": '/doʊnt ˈwʌr.i/',

  // Numbers
  'zero': '/ˈzɪə.roʊ/',
  'one': '/wʌn/',
  'two': '/tuː/',
  'three': '/θriː/',
  'four': '/fɔːr/',
  'five': '/faɪv/',
  'six': '/sɪks/',
  'seven': '/ˈsev.ən/',
  'eight': '/eɪt/',
  'nine': '/naɪn/',
  'ten': '/ten/',
  'eleven': '/ɪˈlev.ən/',
  'twelve': '/twelv/',
  'thirteen': '/ˌθɜːrˈtiːn/',
  'fourteen': '/ˌfɔːrˈtiːn/',
  'fifteen': '/ˌfɪfˈtiːn/',
  'sixteen': '/ˌsɪkˈstiːn/',
  'seventeen': '/ˌsev.ənˈtiːn/',
  'eighteen': '/ˌeɪˈtiːn/',
  'nineteen': '/ˌnaɪnˈtiːn/',
  'twenty': '/ˈtwen.ti/',
  'thirty': '/ˈθɜːr.ti/',
  'forty': '/ˈfɔːr.ti/',
  'fifty': '/ˈfɪf.ti/',
  'hundred': '/ˈhʌn.drəd/',
  'thousand': '/ˈθaʊ.zənd/',
  'million': '/ˈmɪl.jən/',

  // Days & time words
  'monday': '/ˈmʌn.deɪ/',
  'tuesday': '/ˈtjuːz.deɪ/',
  'wednesday': '/ˈwenz.deɪ/',
  'thursday': '/ˈθɜːrz.deɪ/',
  'friday': '/ˈfraɪ.deɪ/',
  'saturday': '/ˈsæt.ər.deɪ/',
  'sunday': '/ˈsʌn.deɪ/',
  'today': '/təˈdeɪ/',
  'yesterday': '/ˈjes.tər.deɪ/',
  'tomorrow': '/təˈmɒr.oʊ/',
  'week': '/wiːk/',
  'weekend': '/ˈwiːk.end/',
  'day': '/deɪ/',
  'month': '/mʌnθ/',
  'year': '/jɪər/',

  // Months
  'january': '/ˈdʒæn.ju.er.i/',
  'february': '/ˈfeb.ru.er.i/',
  'march': '/mɑːrtʃ/',
  'april': '/ˈeɪ.prəl/',
  'may': '/meɪ/',
  'june': '/dʒuːn/',
  'july': '/dʒuˈlaɪ/',
  'august': '/ˈɔː.ɡəst/',
  'september': '/sepˈtem.bər/',
  'october': '/ɒkˈtoʊ.bər/',
  'november': '/noʊˈvem.bər/',
  'december': '/dɪˈsem.bər/',

  // Colors
  'red': '/red/',
  'blue': '/bluː/',
  'green': '/ɡriːn/',
  'yellow': '/ˈjel.oʊ/',
  'orange': '/ˈɒr.ɪndʒ/',
  'purple': '/ˈpɜːr.pəl/',
  'pink': '/pɪŋk/',
  'black': '/blæk/',
  'white': '/waɪt/',
  'grey': '/ɡreɪ/',
  'gray': '/ɡreɪ/',
  'brown': '/braʊn/',

  // Family
  'mother': '/ˈmʌð.ər/',
  'father': '/ˈfɑː.ðər/',
  'sister': '/ˈsɪs.tər/',
  'brother': '/ˈbrʌð.ər/',
  'daughter': '/ˈdɔː.tər/',
  'son': '/sʌn/',
  'grandmother': '/ˈɡrænd.mʌð.ər/',
  'grandfather': '/ˈɡrænd.fɑː.ðər/',
  'aunt': '/ɑːnt/',
  'uncle': '/ˈʌŋ.kəl/',
  'cousin': '/ˈkʌz.ən/',
  'wife': '/waɪf/',
  'husband': '/ˈhʌz.bənd/',
  'family': '/ˈfæm.ɪ.li/',
  'parents': '/ˈper.ənts/',
  'children': '/ˈtʃɪl.drən/',
  'baby': '/ˈbeɪ.bi/',

  // Common verbs
  'be': '/biː/',
  'have': '/hæv/',
  'do': '/duː/',
  'say': '/seɪ/',
  'get': '/ɡet/',
  'make': '/meɪk/',
  'go': '/ɡoʊ/',
  'know': '/noʊ/',
  'take': '/teɪk/',
  'see': '/siː/',
  'come': '/kʌm/',
  'think': '/θɪŋk/',
  'look': '/lʊk/',
  'want': '/wɒnt/',
  'give': '/ɡɪv/',
  'use': '/juːz/',
  'find': '/faɪnd/',
  'tell': '/tel/',
  'ask': '/æsk/',
  'work': '/wɜːrk/',
  'seem': '/siːm/',
  'feel': '/fiːl/',
  'try': '/traɪ/',
  'leave': '/liːv/',
  'call': '/kɔːl/',
  'keep': '/kiːp/',
  'let': '/let/',
  'begin': '/bɪˈɡɪn/',
  'show': '/ʃoʊ/',
  'hear': '/hɪər/',
  'play': '/pleɪ/',
  'run': '/rʌn/',
  'move': '/muːv/',
  'live': '/lɪv/',
  'believe': '/bɪˈliːv/',
  'hold': '/hoʊld/',
  'bring': '/brɪŋ/',
  'happen': '/ˈhæp.ən/',
  'write': '/raɪt/',
  'read': '/riːd/',
  'sit': '/sɪt/',
  'stand': '/stænd/',
  'lose': '/luːz/',
  'pay': '/peɪ/',
  'meet': '/miːt/',
  'include': '/ɪnˈkluːd/',
  'continue': '/kənˈtɪn.juː/',
  'learn': '/lɜːrn/',
  'change': '/tʃeɪndʒ/',
  'lead': '/liːd/',
  'understand': '/ˌʌn.dərˈstænd/',
  'watch': '/wɒtʃ/',
  'follow': '/ˈfɒl.oʊ/',
  'eat': '/iːt/',
  'drink': '/drɪŋk/',
  'sleep': '/sliːp/',
  'wake': '/weɪk/',
  'walk': '/wɔːk/',
  'talk': '/tɔːk/',
  'listen': '/ˈlɪs.ən/',
  'speak': '/spiːk/',
  'open': '/ˈoʊ.pən/',
  'close': '/kloʊz/',
  'buy': '/baɪ/',
  'sell': '/sel/',
  'travel': '/ˈtræv.əl/',
  'visit': '/ˈvɪz.ɪt/',
  'help': '/help/',
  'wait': '/weɪt/',
  'love': '/lʌv/',
  'like': '/laɪk/',
  'need': '/niːd/',

  // Body parts
  'head': '/hed/',
  'face': '/feɪs/',
  'eye': '/aɪ/',
  'eyes': '/aɪz/',
  'ear': '/ɪər/',
  'ears': '/ɪərz/',
  'nose': '/noʊz/',
  'mouth': '/maʊθ/',
  'teeth': '/tiːθ/',
  'tooth': '/tuːθ/',
  'hair': '/her/',
  'neck': '/nek/',
  'shoulder': '/ˈʃoʊl.dər/',
  'arm': '/ɑːrm/',
  'hand': '/hænd/',
  'finger': '/ˈfɪŋ.ɡər/',
  'back': '/bæk/',
  'chest': '/tʃest/',
  'stomach': '/ˈstʌm.ək/',
  'leg': '/leɡ/',
  'knee': '/niː/',
  'foot': '/fʊt/',
  'feet': '/fiːt/',
  'toe': '/toʊ/',
  'heart': '/hɑːrt/',
  'skin': '/skɪn/',
  'bone': '/boʊn/',
  'blood': '/blʌd/',

  // Places
  'house': '/haʊs/',
  'home': '/hoʊm/',
  'room': '/ruːm/',
  'kitchen': '/ˈkɪtʃ.ɪn/',
  'bedroom': '/ˈbed.ruːm/',
  'bathroom': '/ˈbæθ.ruːm/',
  'living room': '/ˈlɪv.ɪŋ ruːm/',
  'school': '/skuːl/',
  'university': '/ˌjuː.nɪˈvɜːr.sɪ.ti/',
  'hospital': '/ˈhɒs.pɪ.təl/',
  'restaurant': '/ˈres.tər.ɒnt/',
  'supermarket': '/ˈsuː.pər.mɑːr.kɪt/',
  'bank': '/bæŋk/',
  'park': '/pɑːrk/',
  'street': '/striːt/',
  'road': '/roʊd/',
  'city': '/ˈsɪt.i/',
  'town': '/taʊn/',
  'country': '/ˈkʌn.tri/',
  'world': '/wɜːrld/',
  'airport': '/ˈer.pɔːrt/',
  'station': '/ˈsteɪ.ʃən/',
  'hotel': '/hoʊˈtel/',
  'office': '/ˈɒf.ɪs/',
  'store': '/stɔːr/',
  'shop': '/ʃɒp/',
  'market': '/ˈmɑːr.kɪt/',
  'library': '/ˈlaɪ.brer.i/',
  'museum': '/mjuːˈziː.əm/',
  'beach': '/biːtʃ/',
  'mountain': '/ˈmaʊn.tɪn/',
  'river': '/ˈrɪv.ər/',
  'sea': '/siː/',
  'ocean': '/ˈoʊ.ʃən/',
  'forest': '/ˈfɒr.ɪst/',
  'garden': '/ˈɡɑːr.dən/',

  // Food & drink
  'food': '/fuːd/',
  'water': '/ˈwɔː.tər/',
  'bread': '/bred/',
  'rice': '/raɪs/',
  'meat': '/miːt/',
  'fish': '/fɪʃ/',
  'chicken': '/ˈtʃɪk.ɪn/',
  'egg': '/eɡ/',
  'milk': '/mɪlk/',
  'cheese': '/tʃiːz/',
  'coffee': '/ˈkɒf.i/',
  'tea': '/tiː/',
  'juice': '/dʒuːs/',
  'sugar': '/ˈʃʊɡ.ər/',
  'salt': '/sɔːlt/',
  'fruit': '/fruːt/',
  'apple': '/ˈæp.əl/',
  'banana': '/bəˈnɑː.nə/',
  'vegetable': '/ˈvedʒ.tə.bəl/',
  'soup': '/suːp/',
  'salad': '/ˈsæl.əd/',
  'cake': '/keɪk/',
  'dessert': '/dɪˈzɜːrt/',
  'breakfast': '/ˈbrek.fəst/',
  'lunch': '/lʌntʃ/',
  'dinner': '/ˈdɪn.ər/',
  'meal': '/miːl/',

  // Adjectives
  'big': '/bɪɡ/',
  'small': '/smɔːl/',
  'large': '/lɑːrdʒ/',
  'little': '/ˈlɪt.əl/',
  'long': '/lɔːŋ/',
  'short': '/ʃɔːrt/',
  'tall': '/tɔːl/',
  'high': '/haɪ/',
  'low': '/loʊ/',
  'old': '/oʊld/',
  'young': '/jʌŋ/',
  'new': '/njuː/',
  'good': '/ɡʊd/',
  'bad': '/bæd/',
  'great': '/ɡreɪt/',
  'important': '/ɪmˈpɔːr.tənt/',
  'different': '/ˈdɪf.ər.ənt/',
  'same': '/seɪm/',
  'hot': '/hɒt/',
  'cold': '/koʊld/',
  'warm': '/wɔːrm/',
  'cool': '/kuːl/',
  'fast': '/fæst/',
  'slow': '/sloʊ/',
  'easy': '/ˈiː.zi/',
  'difficult': '/ˈdɪf.ɪ.kəlt/',
  'hard': '/hɑːrd/',
  'soft': '/sɒft/',
  'happy': '/ˈhæp.i/',
  'sad': '/sæd/',
  'angry': '/ˈæŋ.ɡri/',
  'afraid': '/əˈfreɪd/',
  'tired': '/ˈtaɪərd/',
  'busy': '/ˈbɪz.i/',
  'free': '/friː/',
  'rich': '/rɪtʃ/',
  'poor': '/pɔːr/',
  'beautiful': '/ˈbjuː.tɪ.fəl/',
  'ugly': '/ˈʌɡ.li/',
  'clean': '/kliːn/',
  'dirty': '/ˈdɜːr.ti/',
  'healthy': '/ˈhel.θi/',
  'sick': '/sɪk/',
  'strong': '/strɒŋ/',
  'weak': '/wiːk/',
  'right': '/raɪt/',
  'wrong': '/rɒŋ/',
  'true': '/truː/',
  'false': '/fɔːls/',
  'closed': '/kloʊzd/',
  'full': '/fʊl/',
  'empty': '/ˈemp.ti/',
  'ready': '/ˈred.i/',
  'sunny': '/ˈsʌn.i/',
  'rainy': '/ˈreɪ.ni/',
  'cloudy': '/ˈklaʊ.di/',
  'foggy': '/ˈfɒɡ.i/',
  'humid': '/ˈhjuː.mɪd/',

  // Common nouns
  'man': '/mæn/',
  'woman': '/ˈwʊm.ən/',
  'boy': '/bɔɪ/',
  'girl': '/ɡɜːrl/',
  'person': '/ˈpɜːr.sən/',
  'people': '/ˈpiː.pəl/',
  'friend': '/frend/',
  'teacher': '/ˈtiːtʃ.ər/',
  'student': '/ˈstjuː.dənt/',
  'doctor': '/ˈdɒk.tər/',
  'nurse': '/nɜːrs/',
  'police': '/pəˈliːs/',
  'time': '/taɪm/',
  'place': '/pleɪs/',
  'thing': '/θɪŋ/',
  'problem': '/ˈprɒb.ləm/',
  'life': '/laɪf/',
  'part': '/pɑːrt/',
  'child': '/tʃaɪld/',
  'case': '/keɪs/',
  'company': '/ˈkʌm.pə.ni/',
  'money': '/ˈmʌn.i/',
  'book': '/bʊk/',
  'word': '/wɜːrd/',
  'phone': '/foʊn/',
  'car': '/kɑːr/',
  'door': '/dɔːr/',
  'window': '/ˈwɪn.doʊ/',
  'table': '/ˈteɪ.bəl/',
  'chair': '/tʃer/',
  'bed': '/bed/',
  'bag': '/bæɡ/',
  'key': '/kiː/',
  'letter': '/ˈlet.ər/',
  'name': '/neɪm/',
  'number': '/ˈnʌm.bər/',
  'question': '/ˈkwes.tʃən/',
  'answer': '/ˈæn.sər/',
  'idea': '/aɪˈdɪə/',
  'story': '/ˈstɔːr.i/',
  'example': '/ɪɡˈzæm.pəl/',
  'language': '/ˈlæŋ.ɡwɪdʒ/',
  'english': '/ˈɪŋ.ɡlɪʃ/',
  'spanish': '/ˈspæn.ɪʃ/',

  // Weather & nature
  'weather': '/ˈweð.ər/',
  'sun': '/sʌn/',
  'rain': '/reɪn/',
  'snow': '/snoʊ/',
  'wind': '/wɪnd/',
  'cloud': '/klaʊd/',
  'storm': '/stɔːrm/',
  'temperature': '/ˈtem.prɪ.tʃər/',

  // Transport
  'bus': '/bʌs/',
  'train': '/treɪn/',
  'plane': '/pleɪn/',
  'bicycle': '/ˈbaɪ.sɪ.kəl/',
  'bike': '/baɪk/',
  'taxi': '/ˈtæk.si/',
  'subway': '/ˈsʌb.weɪ/',
  'ticket': '/ˈtɪk.ɪt/',
  'passport': '/ˈpæs.pɔːrt/',

  // Clothing
  'shirt': '/ʃɜːrt/',
  'pants': '/pænts/',
  'dress': '/dres/',
  'shoes': '/ʃuːz/',
  'hat': '/hæt/',
  'coat': '/koʊt/',
  'jacket': '/ˈdʒæk.ɪt/',
  'socks': '/sɒks/',
  'jeans': '/dʒiːnz/',
  'skirt': '/skɜːrt/',

  // Technology
  'computer': '/kəmˈpjuː.tər/',
  'internet': '/ˈɪn.tər.net/',
  'email': '/ˈiː.meɪl/',
  'website': '/ˈweb.saɪt/',
  'password': '/ˈpæs.wɜːrd/',
  'camera': '/ˈkæm.ər.ə/',
  'screen': '/skriːn/',
  'keyboard': '/ˈkiː.bɔːrd/',
  'mouse': '/maʊs/',
  'printer': '/ˈprɪn.tər/',

  // Question words
  'what': '/wɒt/',
  'where': '/wer/',
  'when': '/wen/',
  'who': '/huː/',
  'why': '/waɪ/',
  'how': '/haʊ/',
  'which': '/wɪtʃ/',
  'whose': '/huːz/',

  // Prepositions
  'in': '/ɪn/',
  'on': '/ɒn/',
  'at': '/æt/',
  'to': '/tuː/',
  'for': '/fɔːr/',
  'with': '/wɪð/',
  'from': '/frɒm/',
  'of': '/ɒv/',
  'by': '/baɪ/',
  'about': '/əˈbaʊt/',
  'between': '/bɪˈtwiːn/',
  'through': '/θruː/',
  'during': '/ˈdjʊər.ɪŋ/',
  'before': '/bɪˈfɔːr/',
  'after': '/ˈæf.tər/',
  'above': '/əˈbʌv/',
  'below': '/bɪˈloʊ/',
  'near': '/nɪər/',
  'next to': '/nekst tuː/',
  'behind': '/bɪˈhaɪnd/',
  'in front of': '/ɪn frʌnt əv/',

  // Personal vocabulary (hand-verified)
  'weird': '/wɪrd/',
  'odd': '/ɒd/',
  'creepy': '/ˈkriː.pi/',
  'annoying': '/əˈnɔɪ.ɪŋ/',
  'whole': '/hoʊl/',
  'stuff': '/stʌf/',
  'headache': '/ˈhed.eɪk/',
  'quint': '/kwɪnt/',
  'trolling': '/ˈtroʊl.ɪŋ/',
  'teasing': '/ˈtiː.zɪŋ/',
  'harassing': '/həˈræs.ɪŋ/',
  'nerves': '/nɜːrvz/',
  'behave': '/bɪˈheɪv/',
  'treat': '/triːt/',
  'apologize': '/əˈpɒl.ə.dʒaɪz/',
  'proof': '/pruːf/',
  'prove': '/pruːv/',
  'quote': '/kwoʊt/',
  'thought': '/θɔːt/',
  'otherwise': '/ˈʌð.ər.waɪz/',
  'slipped': '/slɪpt/',
  'sear': '/sɪr/',
  'damn': '/dæm/',
  'dumbass': '/ˈdʌm.æs/',
  'struggles': '/ˈstrʌɡ.əlz/',
  'charge': '/tʃɑːrdʒ/',
  'aware': '/əˈwer/',
  'gestures': '/ˈdʒes.tʃərz/',
  'loud': '/laʊd/',
  'gist': '/dʒɪst/',
  'bunch': '/bʌntʃ/',
  'acronym': '/ˈæk.rə.nɪm/',
  'huge': '/hjuːdʒ/',
  'either': '/ˈiː.ðər/',
  'unpleasant': '/ʌnˈplez.ənt/',
  'unbothered': '/ʌnˈbɒð.ərd/',
  'dizzy': '/ˈdɪz.i/',
  'numb': '/nʌm/',
  'squeeze': '/skwiːz/',
  'gripping': '/ˈɡrɪp.ɪŋ/',
  'sunburned': '/ˈsʌn.bɜːrnd/',
  'scalp': '/skælp/',
  'balding': '/ˈbɔːl.dɪŋ/',
  'tough': '/tʌf/',
  'flavor': '/ˈfleɪ.vər/',
  'oatmeal': '/ˈoʊt.miːl/',
  'almond': '/ˈɑː.mənd/',
  'nougat': '/ˈnuː.ɡət/',
  'licorice': '/ˈlɪk.ər.ɪʃ/',
  'delight': '/dɪˈlaɪt/',
  'starve to death': '/stɑːrv tə deθ/',
  'spicy': '/ˈspaɪ.si/',
  'cacti': '/ˈkæk.taɪ/',
  'cactuses': '/ˈkæk.tə.sɪz/',
  'cliff': '/klɪf/',
  'fridge': '/frɪdʒ/',
  'bumpy': '/ˈbʌm.pi/',
  'trippy': '/ˈtrɪp.i/',
  'spatula': '/ˈspætʃ.ə.lə/',
  'stash': '/stæʃ/',
  'cuz': '/kʌz/',
  'goodness': '/ˈɡʊd.nəs/',
  'stan': '/stæn/',
  'hangout': '/ˈhæŋ.aʊt/',
  'hang out': '/hæŋ aʊt/',
  'picky eater': '/ˈpɪk.i ˈiː.tər/',
  'cinnamon': '/ˈsɪn.ə.mən/',
  'quiche': '/kiːʃ/',
  'meatloaf': '/ˈmiːt.loʊf/',
  'mushy': '/ˈmʌʃ.i/',
  'dry': '/draɪ/',
  'spoiled': '/spɔɪld/',
  'powder': '/ˈpaʊ.dər/',
  'crumble': '/ˈkrʌm.bəl/',
  'puff': '/pʌf/',
  'blankets': '/ˈblæŋ.kɪts/',
  'crane': '/kreɪn/',
  'brick': '/brɪk/',
  'jail': '/dʒeɪl/',
  'belt': '/belt/',
  'sheep': '/ʃiːp/',
  'dump': '/dʌmp/',
  'dive': '/daɪv/',
  'crawl': '/krɔːl/',
  'pimple': '/ˈpɪm.pəl/',
  'nasty': '/ˈnæs.ti/',
  'ick': '/ɪk/',
  'harm': '/hɑːrm/',
  'accurate': '/ˈæk.jər.ət/',
  'blunt': '/blʌnt/',
  'immature': '/ˌɪm.əˈtʃʊr/',
  'wise': '/waɪz/',
  'silly': '/ˈsɪl.i/',
  'flaws': '/flɔːz/',
  'misunderstandings': '/ˌmɪs.ʌn.dərˈstæn.dɪŋz/',
  'swear': '/swer/',
  'cheat': '/tʃiːt/',
  'yap': '/jæp/',
  'idk': '/ˌaɪ.diːˈkeɪ/',
  'greed': '/ɡriːd/',
  'cheek': '/tʃiːk/',
  'dimples': '/ˈdɪm.pəlz/',
  'itching': '/ˈɪtʃ.ɪŋ/',
  'kerb': '/kɜːrb/',
  'curb': '/kɜːrb/',
  'camber': '/ˈkæm.bər/',
  'cane': '/keɪn/',
  'sails': '/seɪlz/',
  'nail': '/neɪl/',
  'aid': '/eɪd/',
  'bark': '/bɑːrk/',
  'eagle': '/ˈiː.ɡəl/',
  'nun': '/nʌn/',
  'swag': '/swæɡ/',
  'gatekeep': '/ˈɡeɪt.kiːp/',
  'glide': '/ɡlaɪd/',
  'syllable': '/ˈsɪl.ə.bəl/',
  'sarcasm': '/ˈsɑːr.kæz.əm/',

  // Study unit: suffix example words
  'creation': '/kriˈeɪ.ʃən/',
  'movement': '/ˈmuːv.mənt/',
  'happiness': '/ˈhæp.i.nəs/',
  'ability': '/əˈbɪl.ə.ti/',
  'artist': '/ˈɑːr.tɪst/',
  'friendship': '/ˈfrend.ʃɪp/',
  'childhood': '/ˈtʃaɪld.hʊd/',
  'helpful': '/ˈhelp.fəl/',
  'careless': '/ˈkeər.ləs/',
  'comfortable': '/ˈkʌmf.tə.bəl/',
  'dangerous': '/ˈdeɪn.dʒər.əs/',
  'creative': '/kriˈeɪ.tɪv/',
  'musical': '/ˈmjuː.zɪ.kəl/',
  'childish': '/ˈtʃaɪl.dɪʃ/',
  'organize': '/ˈɔːr.ɡən.aɪz/',
  'simplify': '/ˈsɪm.plɪ.faɪ/',
  'widen': '/ˈwaɪ.dən/',
  'activate': '/ˈæk.tɪ.veɪt/',
  'quickly': '/ˈkwɪk.li/',
  'backward': '/ˈbæk.wərd/',
  'clockwise': '/ˈklɒk.waɪz/',

  // Study unit: phoneme example words
  'ship': '/ʃɪp/',
  'cat': '/kæt/',
  'cup': '/kʌp/',
  'bird': '/bɜːrd/',
  'my': '/maɪ/',
  'now': '/naʊ/',
  'here': '/hɪər/',
  'tour': '/tʊər/',
  'this': '/ðɪs/',
  'she': '/ʃiː/',
  'measure': '/ˈmeʒ.ər/',
  'job': '/dʒɒb/',
  'sing': '/sɪŋ/',
  'van': '/væn/',
};

export function getPhonetic(text: string): string | null {
  const key = text.toLowerCase().trim();
  // Only return hand-verified transcriptions. We intentionally do NOT
  // auto-generate IPA: a rule-based guess is wrong for most English words,
  // and showing an incorrect transcription is worse than showing none.
  return ipaDict[key] ?? null;
}

// --- Voice selection (global) -------------------------------------------------

const VOICE_STORAGE_KEY = 'ef-voice-uri';

/** Read the globally selected voice URI (persisted in localStorage). */
export function getSelectedVoiceURI(): string | null {
  if (typeof window === 'undefined') return null;
  try {
    return window.localStorage.getItem(VOICE_STORAGE_KEY);
  } catch {
    return null;
  }
}

/** Persist the globally selected voice URI. Empty string clears it (system default). */
export function setSelectedVoiceURI(uri: string | null): void {
  if (typeof window === 'undefined') return;
  try {
    if (uri) window.localStorage.setItem(VOICE_STORAGE_KEY, uri);
    else window.localStorage.removeItem(VOICE_STORAGE_KEY);
  } catch {
    /* ignore */
  }
}

/** List the available English text-to-speech voices in this browser. */
export function getEnglishVoices(): SpeechSynthesisVoice[] {
  if (typeof window === 'undefined' || !window.speechSynthesis) return [];
  return window.speechSynthesis
    .getVoices()
    .filter((v) => v.lang.toLowerCase().startsWith('en'));
}

export function speakText(text: string, lang = 'en-US'): void {
  if (typeof window === 'undefined' || !window.speechSynthesis) return;
  window.speechSynthesis.cancel();
  const utterance = new SpeechSynthesisUtterance(text);
  utterance.lang = lang;
  utterance.rate = 0.85;
  utterance.pitch = 1;

  // Apply the globally selected voice if it is available.
  const uri = getSelectedVoiceURI();
  if (uri) {
    const voice = window.speechSynthesis.getVoices().find((v) => v.voiceURI === uri);
    if (voice) {
      utterance.voice = voice;
      utterance.lang = voice.lang;
    }
  }

  window.speechSynthesis.speak(utterance);
}
